// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8eQKzVBTE6zwGf4SQcX_d7tFv40WfA3E',
    appId: '1:19860377354:web:3d160fc7d6d09e631a34f3',
    messagingSenderId: '19860377354',
    projectId: 'my-shop-project-329311',
    authDomain: 'my-shop-project-329311.firebaseapp.com',
    storageBucket: 'my-shop-project-329311.appspot.com',
    measurementId: 'G-R56HNFBM2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJC96-uikgiUcwEhmZtyGurtZaZT3hobI',
    appId: '1:19860377354:android:b8d3b87eb29f6bed1a34f3',
    messagingSenderId: '19860377354',
    projectId: 'my-shop-project-329311',
    storageBucket: 'my-shop-project-329311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYXNWL97FfE-c_jBXHcEgefD-W8_faubg',
    appId: '1:19860377354:ios:764d780f317439ca1a34f3',
    messagingSenderId: '19860377354',
    projectId: 'my-shop-project-329311',
    storageBucket: 'my-shop-project-329311.appspot.com',
    iosClientId: '19860377354-j5hvkj2jj5p17lo9lprdvt326cdrq43l.apps.googleusercontent.com',
    iosBundleId: 'com.example.authlogin',
  );
}
